"""KVIC cluster schemas."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.batch import BatchListItem


class ClusterBase(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cluster_name: str = Field(min_length=3, max_length=160, examples=["Tenali Beekeeping Cluster"])
    district: str = Field(min_length=2, max_length=80, examples=["Guntur"])
    state: str = Field(min_length=2, max_length=80, examples=["Andhra Pradesh"])
    description: str | None = Field(default=None, max_length=1000)
    coordinator_name: str | None = Field(default=None, max_length=120)
    coordinator_phone: str | None = Field(default=None, max_length=20)

    @field_validator("cluster_name", "district", "state")
    @classmethod
    def _clean_required(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if len(cleaned) < 2:
            raise ValueError("This field must contain at least 2 characters")
        return cleaned

    @field_validator("coordinator_phone")
    @classmethod
    def _clean_phone(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip().replace(" ", "").replace("-", "")
        if not cleaned:
            return None
        if not cleaned.startswith("+") and cleaned.isdigit() and len(cleaned) == 10:
            cleaned = f"+91{cleaned}"
        if not (cleaned.startswith("+") and cleaned[1:].isdigit() and 8 <= len(cleaned) <= 16):
            raise ValueError("Enter a valid phone number, e.g. 9876543210 or +919876543210")
        return cleaned


class ClusterCreate(ClusterBase):
    """``POST /api/v1/clusters``.

    ``cluster_code`` is optional: omit it and the backend generates one
    (``KVIC-GNT-001``); supply it only when migrating an existing registry.
    """

    cluster_code: str | None = Field(
        default=None,
        max_length=40,
        description="Optional. Generated by the backend when omitted.",
        examples=["KVIC-GNT-001"],
    )

    reassign: bool = Field(
        default=False,
        description=(
            "Move batches that already belong to another cluster. Requires the "
            "deliberate confirmation the form shows; without it the request is "
            "refused with the list of what each batch currently belongs to."
        ),
    )
    batch_ids: list[uuid.UUID] = Field(
        default_factory=list,
        description=(
            "Optional. Real honey batches to place in the new cluster, in the same "
            "transaction as the cluster itself — so a cluster is never created empty "
            "by a write that failed half way. The batches are the beekeepers' own "
            "records; only their cluster link is written."
        ),
    )

    @field_validator("cluster_code")
    @classmethod
    def _clean_code(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip().upper().replace(" ", "-")
        return cleaned or None


class ClusterUpdate(BaseModel):
    """``PUT /api/v1/clusters/{id}`` — partial update of editable fields."""

    model_config = ConfigDict(extra="forbid")

    cluster_name: str | None = Field(default=None, min_length=3, max_length=160)
    district: str | None = Field(default=None, min_length=2, max_length=80)
    state: str | None = Field(default=None, min_length=2, max_length=80)
    description: str | None = Field(default=None, max_length=1000)
    coordinator_name: str | None = Field(default=None, max_length=120)
    coordinator_phone: str | None = Field(default=None, max_length=20)

    @field_validator("coordinator_phone")
    @classmethod
    def _clean_phone(cls, value: str | None) -> str | None:
        return ClusterBase._clean_phone(value)


class ClusterBatchCandidate(BatchListItem):
    """A real batch offered to a cluster's *Add batches* picker.

    Everything above is the batch's own record — batch code, harvest, beekeeper,
    quantity, stage status — exactly as the batch list shows it. The three extra
    fields state, in the picker's own words, where the batch currently sits, so a
    batch that belongs to another cluster is visibly flagged *before* it is chosen
    rather than refused afterwards with no explanation.
    """

    in_this_cluster: bool = False
    placement: Literal["unassigned", "this_cluster", "other_cluster"] = "unassigned"
    placement_label: str = "No cluster assigned"
    requires_confirmation: bool = False


def to_batch_candidate(item: BatchListItem, cluster_id: uuid.UUID) -> ClusterBatchCandidate:
    """State the batch's current cluster placement without changing anything.

    Nothing is written and nothing is hidden: the label names the cluster the
    batch actually belongs to, and ``requires_confirmation`` is the flag the
    picker uses to demand a deliberate move.
    """
    if item.cluster_id is None:
        placement, label, confirm = "unassigned", "No cluster assigned", False
    elif item.cluster_id == cluster_id:
        placement, label, confirm = "this_cluster", "Already in this cluster", False
    else:
        cluster = item.cluster_code or item.cluster_name or "another cluster"
        placement = "other_cluster"
        label = f"Currently in {cluster} — moving it must be confirmed"
        confirm = True
    return ClusterBatchCandidate(
        **item.model_dump(),
        in_this_cluster=item.cluster_id == cluster_id,
        placement=placement,
        placement_label=label,
        requires_confirmation=confirm,
    )


class ClusterBatchAssign(BaseModel):
    """``POST /api/v1/clusters/{id}/batches`` — place batches in a cluster.

    ``reassign`` is the explicit action the platform requires before a batch that
    already belongs to another cluster is moved: the move updates that batch's own
    cluster link, it never creates a second relationship. Without it, such a batch
    is reported in a 409 rather than silently taken.
    """

    model_config = ConfigDict(extra="forbid")

    batch_ids: list[uuid.UUID] = Field(min_length=1, max_length=200)
    reassign: bool = Field(
        default=False,
        description="Move batches that already belong to another cluster, deliberately.",
    )


class ClusterBatchAssignResult(BaseModel):
    """What the placement actually did, in batch codes."""

    cluster_id: uuid.UUID
    cluster_code: str
    assigned: list[str] = Field(default_factory=list)
    moved: list[str] = Field(default_factory=list)
    already: list[str] = Field(default_factory=list)
    batch_count: int = 0
    reassigned: bool = False


class ClusterBatchDetachResult(BaseModel):
    """What the removal actually did."""

    cluster_id: uuid.UUID
    cluster_code: str
    detached: str
    batch_count: int = 0


class ClusterBatchTotals(BaseModel):
    batches: int = 0
    collections: int = 0
    beekeepers_represented: int = 0
    hives_behind_them: int = 0
    packages: int = 0
    quantity_collected: Decimal = Decimal("0")
    quantity_packaged: Decimal = Decimal("0")
    unit: str | None = None
    mixed_units: bool = False


class ClusterStageBreakdown(BaseModel):
    """How much of the cluster's honey has reached each stage.

    Cumulative by nature — honey cannot be delivered without having been
    collected — and read from the batches' own stage records, never from a
    per-cluster status somebody maintains.
    """

    collection: int = 0
    processing: int = 0
    laboratory: int = 0
    packaging: int = 0
    distribution: int = 0
    delivered: int = 0


class ClusterBatchAnalytics(BaseModel):
    """The cluster's production figures, every one of them a count of real rows."""

    cluster_id: uuid.UUID
    totals: ClusterBatchTotals
    status_breakdown: ClusterStageBreakdown
    by_status: dict[str, int] = Field(default_factory=dict)
    processing: dict[str, int] = Field(default_factory=dict)
    laboratory: dict[str, int] = Field(default_factory=dict)
    packaging: dict[str, Any] = Field(default_factory=dict)
    distribution: dict[str, int] = Field(default_factory=dict)
    generated_at: datetime


class ClusterStatusUpdate(BaseModel):
    """``PATCH /api/v1/clusters/{id}/status``."""

    model_config = ConfigDict(extra="forbid")

    is_active: bool
    reason: str | None = Field(default=None, max_length=200)


class ClusterPublic(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    cluster_code: str
    cluster_name: str
    district: str
    state: str
    description: str | None = None
    coordinator_name: str | None = None
    coordinator_phone: str | None = None
    is_active: bool
    created_at: datetime
    updated_at: datetime


class ClusterWithCounts(ClusterPublic):
    """Cluster plus its member and batch counts (database aggregates, not estimates)."""

    member_count: int = 0
    #: Honey batches currently placed in this cluster, counted from
    #: ``honey_batches.cluster_id``. It is the same number the cluster's own batch
    #: table has rows, so the register can never promise more than it shows.
    batch_count: int = 0


class ClusterDependencies(BaseModel):
    """What is recorded under a cluster, each figure counted from its own table.

    Read before a deletion, and shown on the cluster's page, because the two
    questions are the same question: *is anything here?* A cluster with records
    under it is history — honey that was harvested, packed and shipped — and
    history is not deleted to tidy a register.
    """

    beekeepers: int = 0
    hives: int = 0
    collections: int = 0
    batches: int = 0
    laboratory_tests: int = 0
    packaging_runs: int = 0
    packages: int = 0
    #: Shipments raised off this cluster's batches — the last stage of the chain,
    #: counted through the packages that came off its honey.
    shipments: int = 0

    @property
    def total(self) -> int:
        return (
            self.beekeepers
            + self.hives
            + self.collections
            + self.batches
            + self.laboratory_tests
            + self.packaging_runs
            + self.packages
            + self.shipments
        )

    def as_counts(self) -> dict[str, int]:
        """The counts as a screen reads them, named as a person would name them."""
        return {
            "Beekeepers": self.beekeepers,
            "Hives": self.hives,
            "Collections": self.collections,
            "Batches": self.batches,
            "Laboratory tests": self.laboratory_tests,
            "Packaging runs": self.packaging_runs,
            "Packages": self.packages,
            "Shipments": self.shipments,
        }


class ClusterDetail(BaseModel):
    cluster: ClusterPublic
    member_count: int = 0
    members: list[dict] = Field(default_factory=list)
    #: Everything recorded under this cluster. Dynamic, counted from the tables.
    dependencies: ClusterDependencies = Field(default_factory=ClusterDependencies)
    #: Whether the cluster may be removed at all, and why not when it may not.
    can_delete: bool = False
    delete_blocked_reason: str | None = None


class ClusterDeleteRequest(BaseModel):
    """``DELETE /api/v1/clusters/{id}``."""

    model_config = ConfigDict(extra="forbid")

    reason: str | None = Field(
        default=None,
        max_length=300,
        description="Why the cluster is being removed. Recorded in the audit log.",
    )
    confirm: bool = Field(
        default=False,
        description=(
            "Must be true. Removing a cluster is deliberate, and a stray request must not do it."
        ),
    )


# --------------------------------------------------------------------------- #
# Projections
# --------------------------------------------------------------------------- #
def to_cluster_public(cluster, member_count: int = 0, batch_count: int = 0) -> ClusterWithCounts:
    """Cluster plus its member and batch counts.

    Both counts are passed in from single aggregate queries rather than read from
    ``cluster.beekeepers`` / ``cluster.batches``, which would trigger one SELECT
    per row when listing clusters.
    """
    return ClusterWithCounts(
        id=cluster.id,
        cluster_code=cluster.cluster_code,
        cluster_name=cluster.cluster_name,
        district=cluster.district,
        state=cluster.state,
        description=cluster.description,
        coordinator_name=cluster.coordinator_name,
        coordinator_phone=cluster.coordinator_phone,
        is_active=cluster.is_active,
        created_at=cluster.created_at,
        updated_at=cluster.updated_at,
        member_count=member_count,
        batch_count=batch_count,
    )


__all__ = [
    "ClusterCreate",
    "ClusterUpdate",
    "ClusterStatusUpdate",
    "ClusterPublic",
    "ClusterWithCounts",
    "ClusterDetail",
    "ClusterBatchAssign",
    "ClusterBatchAssignResult",
    "ClusterBatchCandidate",
    "to_batch_candidate",
    "ClusterBatchDetachResult",
    "ClusterBatchAnalytics",
    "ClusterBatchTotals",
    "ClusterStageBreakdown",
    "to_cluster_public",
]
